### PR TITLE
Adding support for django 4

### PR DESCRIPTION
**Pull request by asucrews**
Adding support for django 4

Not sure how to remove the warning for related name

Adding #61 and #58

### CODE REVIEW

**Comment by FlipperPA** [comment]
Any chance we can get this reviewed and merged, @Paessler? Thanks so much for the package!

**Comment by mqarty** [comment]
+1

**Comment by FlipperPA** [comment]
@waltronix @konstantinpae @AlexanderBodin @MattesWhite Any chance of getting eyes on this PR? Trying to avoid splintering the package...

**Comment by FlipperPA** [comment]
Thanks for the continued improvements, @asucrews!

**Comment by rgs258** [comment]
@belugame this looks like a great PR - could we please trouble you for a looksee?

**Comment by belugame** [comment]
Jesus said... Ask and you shall receive a looksee :eyes:

**Comment by rgs258** [comment]
🙌

**Comment by FlipperPA** [comment]
Thank you for the merge, @belugame! 💯

**Comment by rgs258** [comment]
@belugame sorry to be a thorn - I wonder if you might be able to cut a release to PyPi? If that's just scheduled for later, no worries and I can wait for it. Just checking.

Thanks again for maintaining this package!

**Comment by belugame** [comment]
@rgs258 sorry, I no longer have the permissions to create a release / no longer am member of the organisation account. Your best bet would be to write a friendly email to the author_email specified in the setup.py.

**Comment by vQuadX** [comment]
@belugame please, create tag for pin requirements

**Comment by N1K1TAS95** [comment]
@alfonsrv I've just gave up and created my custom package...

**Comment by kairichard** [comment]
I am kinda sad to see the open source efforts deteriorate at Paessler. Once I used to work there were we conceived the initial guide on how to open source the libraries we used internally and for some time that seems work really well including maintaining them. No idea what happened since then.

I feel like apologising on behalf of the all the colleagues that were part of our team back then.

@Normos @Eorhim @zsoldosp @belugame @Joern Paessler @Michael Zeidler (RIP)

**Comment by djjudas21** [comment]
I was using another Python project that got abandoned, but someone managed to request a takeover of the abandoned PyPI account and continue publishing under the same name. Might be worth considering here? https://github.com/hMatoba/Piexif/issues/122#issuecomment-1175590297

**Comment by bjenmonk** [comment]
I like this package
I am using Django 4.2.1 and django-currentuser 0.5.3
I commented out "Requires-Dist: Django (<3.3,>=1.11.17) ; python_version >= "2.7"" in site-packages/django_currentuser-0.5.3.dist-info/METADATA
All good. The package works as expected

**Comment by zsoldosp** [comment]
FYI, the repo has just been transferred to me. We are working on the pypi side of transfer too.

Once that is done, I'll look at getting it released

**Comment by FlipperPA** [comment]
Awesome @zsoldosp - let me know if we can help with anything. I've got some experience transferring ownership on PyPI.

**Comment by zsoldosp** [comment]
> [...] let me know if we can help with anything. I've got some experience transferring ownership on PyPI.

My understanding is that adding me in the “Collaborators” section as Owner in the settings on pypi.org should do the trick (and then I can remove the old owner). Is there something more to it, @FlipperPA ?

**Comment by FlipperPA** [comment]
@zsoldosp That should do it, just make sure you get added as `OWNER` and not a maintainer.

I've also taken over a dead project before without the owner's help, which is a much more involved process. I'm glad to hear you're getting this one on your own.

Consider finding some other folks who contribute and you trust to be owners too! I try to have multiple owners for my projects... with a mix of success:

image

Thanks again for stepping up to the plate!

**Pull request merged**
