### PR TITLE
CurrentUserField: add support for update on save

### PR DESCRIPTION
**Pull request by felubra**
This implements #36 .

### CODE REVIEW

**Comment by belugame** [comment]
@felubra  Hey, thank you very much for your contribution. Did you have a look yet at the failing builds on travis?

**Comment by felubra** [comment]
Hi @belugame . Not sure why it is failing. I will spin up a local travis to investigate. Thanks.

**Comment by belugame** [comment]
@felubra  Sorry, we don't get around to spend time on this mini-project.
Does this affect behavior in any way for existing installations?

**Comment by felubra** [comment]
@belugame I don't think so, the user has to enable to explicitly set `on_update=True`, so the default behavior is to not use the new feature on existing installations. Additional test coverage was provided to test the scenario with the new flag set to False also ([see here](https://github.com/PaesslerAG/django-currentuser/pull/37/commits/94bf67e20534a1c13458ce73f74f2ab99e70d8d6#diff-9791b30deacf55dadd61e57aba1196d3R167-R188)).

**Comment by belugame** [comment]
understood. Can we do without the migration file in the testapp?

**Comment by felubra** [comment]
Migrations are necessary for tests that target django 2.2, since:
> Tests will fail on SQLite if apps without migrations have relations to apps with migrations. This has been a documented restriction since migrations were added in Django 1.7, but it fails more reliably now. You’ll see tests failing with errors like no such table: <app_label>_<model>. This was observed with several third-party apps that had models in tests without migrations. You must add migrations for such models. ([Django 2.2 release notes](https://docs.djangoproject.com/en/2.2/releases/2.2/#miscellaneous))

I've added two models for testing the new feature (`TestModelOnUpdate` and `TestModelDefaultBehavior`). The existence of these without the migrations will trigger this Django 2.2 behavior.

In other words, without the migrations the CI job will fail whenever it tries to test Django version 2.2: 
- https://travis-ci.org/felubra/django-currentuser/jobs/654120305?utm_medium=notification&utm_source=github_status
- https://travis-ci.org/felubra/django-currentuser/jobs/654120306?utm_medium=notification&utm_source=github_status
- https://travis-ci.org/felubra/django-currentuser/jobs/654120307?utm_medium=notification&utm_source=github_status

This behavior, strange as it may seem, does not happen if we update the build of travis to run on Ubuntu 18.04 (bionic), so I believe the problem is related to the version of the sqlite3 library provided in Ubuntu 16.04.

- https://travis-ci.org/felubra/django-currentuser/builds/654122299?utm_medium=notification&utm_source=github_status

In any case, this is a problem with testing and a specific version of Django. I’m open for additional suggestions on how we can resolve it.

**Comment by belugame** [comment]
Thank you very much for the explanation and your work. Sorry again for the tardy replies here, I can understand that that is frustrating.

**Comment by belugame** [comment]
I just released it as 0.5.0

**Comment by felubra** [comment]
> Thank you very much for the explanation and your work. Sorry again for the tardy replies here, I can understand that that is frustrating.

No problems - your concerns were valid. I'm happy to help, thank you!

**Pull request merged**
