### PR TITLE
Resolve RemovedInDjango40Warning warning in Django 3

### PR DESCRIPTION
**Pull request by fgs-dbudwin**
Using Django version 3.* with this library will cause the following warning to be displayed:

```
lib/python3.8/site-packages/django_currentuser/db/models/fields.py:13: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```

This simple pull request fixes the warning by implementing the fix suggested by Django.

### CODE REVIEW

**Comment by belugame** [comment]
Thank you for the fix :+1: 
Would be great if you increase the bugfix version for a new release

**Comment by fgs-dbudwin** [comment]
Will do, I'll do it first thing in the morning.

**Comment by fgs-dbudwin** [comment]
@belugame I updated this PR with the incremented version number--please let me know if I can assist further.

**Comment by belugame** [comment]
great, thank you for the contribution. Once the build has passed i will merge and release

**Pull request merged**
