### PR TITLE
bugfix: should support Django 1.11.1 (issue #9)

### PR DESCRIPTION
**Pull request by zsoldosp**
see #9

### CODE REVIEW

**Comment by zsoldosp** [comment]
@kairichard / @belugame - could you review & if all ok merge/release?

**Comment by kairichard** [comment]
LGTM. And thanks for the quick response.

**Comment by zsoldosp** [comment]
@kairichard btw, didn't we add something in the cookiecutter template to check against this specifically? something like a `pip list --outdated` or similar?

**Comment by kairichard** [comment]
@zsoldosp Yes that has been backported from https://github.com/PaesslerAG/django-admin-caching/pull/7/files into the template 6 months ago.

**Comment by kairichard** [comment]
@zsoldosp It also fails the daily builds as there is no support for django 2.0 https://github.com/PaesslerAG/django-admin-caching/. 

I opened a ticket for that - https://github.com/PaesslerAG/django-admin-caching/issues/14

**Pull request merged**
