### PR TITLE
support Django 2.0 fixes #12

### LINKED ISSUE #12: Support for Django 2.0
Django 2.0 has been released but this package currently requires 'Django>=1.8,<1.12' as dependency.

### PR DESCRIPTION
**Pull request by zsoldosp**
see #9 , #12

### CODE REVIEW

**Comment by kairichard** [comment]
@zsoldosp the travis.yml also needs to learn the new environment in order to publicly reflect what versions are supported.

**Comment by zsoldosp** [comment]
@kairichard could you run `tox2travis.py` and commit? I don't actually have a working py env  (and add it as a check to the `Makefile` so it fails if the generated output is different)

**Comment by belugame** [comment]
@zsoldosp  running tox2travis.py only reorders the envs from 3.4, 3.5, 3.6 to 3.4, 3.6, 3.5

**Comment by zsoldosp** [comment]
@belugame did you check before or after 4634fd0?

**Comment by zsoldosp** [comment]
@kairichard @belugame right now I don't have the time & the upgrade to 2.0 needs actual logic change (`AttributeError: 'CurrentUserField' object has no attribute 'rel'`), and for the coming weeks I don't have the free time to deal with that. Could you please either finish it based on this branch, or open an issue and reference this pull? Thanks

**Comment by kairichard** [comment]
@zsoldosp Thanks for taking this off the ground we will try to finish based on the work you already put into it.

**Comment by belugame** [comment]
@zsoldosp  It was after/with 4634fd0

**Comment by zsoldosp** [comment]
@belugame then it makes sense it just reordered it (windows vs. mac, python version diff I assume), as I've updated the `.travis.yml` file already :)

**Comment by zsoldosp** [comment]
@belugame thanks!

@kairichard the autorelease is still in place, i.e.: if I merge it, it'll be published to pypi, right?

**Comment by kairichard** [comment]
@zsoldosp yes it's still humming away

**Pull request merged**
